services:
  roulette:
    build:
      context: ./
    env_file: .env
    hostname: roll
    logging:
      options:
        max-size: "1m"
        max-file: 1
    restart: unless-stopped
    volumes:
      - ./config/settings.toml:/amazake/config/settings.toml:ro # Readonly
      - ./config/settings.local.toml:/amazake/config/settings.local.toml:ro # Readonly
      - ./config/.secrets.toml:/amazake/config/.secrets.toml:ro # Readonly
      - ./config/.secrets.local.toml:/amazake/config/.secrets.local.toml:ro # Readonly