# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extensions/roulette/action/proto/action.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'extensions/roulette/action/proto/action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-extensions/roulette/action/proto/action.proto\x12\x19\x65xt.roulette.action.proto\x1a\x19google/protobuf/any.proto\"\xbb\x05\n\x06\x41\x63tion\x12\'\n\x07unknown\x18\x01 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12<\n\x07timeout\x18\x02 \x01(\x0b\x32).ext.roulette.action.proto.Action.TimeoutH\x00\x12I\n\x0etemporary_role\x18\x03 \x01(\x0b\x32/.ext.roulette.action.proto.Action.TemporaryRoleH\x00\x1am\n\tResponses\x12\x15\n\raffected_self\x18\x01 \x03(\t\x12\x16\n\x0e\x61\x66\x66\x65\x63ted_other\x18\x02 \x03(\t\x12\x17\n\x0funaffected_self\x18\x03 \x03(\t\x12\x18\n\x10unaffected_other\x18\x04 \x03(\t\x1a\xb0\x01\n\x07Timeout\x12\x18\n\x0blower_bound\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bupper_bound\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x43\n\tresponses\x18\x03 \x01(\x0b\x32+.ext.roulette.action.proto.Action.ResponsesH\x02\x88\x01\x01\x42\x0e\n\x0c_lower_boundB\x0e\n\x0c_upper_boundB\x0c\n\n_responses\x1a\xd2\x01\n\rTemporaryRole\x12\x18\n\x0blower_bound\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x18\n\x0bupper_bound\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04role\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x43\n\tresponses\x18\x04 \x01(\x0b\x32+.ext.roulette.action.proto.Action.ResponsesH\x03\x88\x01\x01\x42\x0e\n\x0c_lower_boundB\x0e\n\x0c_upper_boundB\x07\n\x05_roleB\x0c\n\n_responsesB\x08\n\x06\x61\x63tionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extensions.roulette.action.proto.action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=104
  _globals['_ACTION']._serialized_end=803
  _globals['_ACTION_RESPONSES']._serialized_start=292
  _globals['_ACTION_RESPONSES']._serialized_end=401
  _globals['_ACTION_TIMEOUT']._serialized_start=404
  _globals['_ACTION_TIMEOUT']._serialized_end=580
  _globals['_ACTION_TEMPORARYROLE']._serialized_start=583
  _globals['_ACTION_TEMPORARYROLE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
