# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extensions/roulette/action/proto/roll.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'extensions/roulette/action/proto/roll.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from extensions.roulette.action.proto import action_pb2 as extensions_dot_roulette_dot_action_dot_proto_dot_action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+extensions/roulette/action/proto/roll.proto\x12\x19\x65xt.roulette.action.proto\x1a-extensions/roulette/action/proto/action.proto\"w\n\x04Roll\x12\x13\n\x06weight\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x12\n\x05\x64\x65lay\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x31\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32!.ext.roulette.action.proto.ActionB\t\n\x07_weightB\x08\n\x06_delayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extensions.roulette.action.proto.roll_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLL']._serialized_start=121
  _globals['_ROLL']._serialized_end=240
# @@protoc_insertion_point(module_scope)
