syntax = "proto3";

package ext.roulette.config;

import "extensions/roulette/action/proto/action.proto";
import "extensions/roulette/action/proto/roll.proto";

message RouletteConfiguration {

  // The Guild this bot will be operating on.
  // Required.
  optional uint64 guild = 1;

  // Channels in the Guild to observe (for regular users).
  // Required.
  repeated uint64 channels = 2;

  // Users considered Administrator-level users.
  // Required.
  repeated uint64 administrators = 3;

  // Roles considered Moderator-level roles.
  // Required.
  repeated uint64 moderator_roles = 4;

  // Roles that are protected from any modification action from the Roulette.
  // Required.
  repeated uint64 protected_roles = 5;

  // A list of regex patterns (Python) that will trigger the Roulette.
  // Required.
  repeated string patterns = 6;

  // A list of Roll configurations that represent the "Roulette".
  // Required.
  repeated ext.roulette.action.proto.Roll rolls = 7;

  // Responses to default to for timeouts (where a roll may not specify).
  // Required.
  optional ext.roulette.action.proto.Action.Responses timeout_response_default = 8;
}